# Generated by Django 5.2.7 on 2025-10-21 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
