# Generated by Django 5.2.7 on 2025-10-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_groups_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
